# Generated by Django 5.2.4 on 2025-07-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tenant_type', models.CharField(choices=[('office', 'Office Tenant'), ('tenant', 'Tenant'), ('kiosk', 'Kiosk')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('coi', 'Certificate of Incorporation'), ('cr12', 'CR12'), ('kra', 'KRA Certificate'), ('id', 'Director/Guarantor ID'), ('kra_pin', 'Director/Guarantor KRA'), ('hots', 'HOTS'), ('lease', 'Lease'), ('license', 'License'), ('invoice', 'Invoice'), ('statement', 'Statement'), ('letter', 'Letter')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='files.tenant')),
            ],
        ),
    ]
