# Generated by Django 5.2.4 on 2025-07-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
    ]
