# Generated by Django 5.2.4 on 2025-07-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20250716_1534'),
        ('files', '0002_auto_add_tenants'),
    ]

    operations = [
    ]
