# Generated by Django 5.2.4 on 2025-07-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_documenttype_tenanttype_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
