# Generated by Django 5.2.4 on 2025-08-18 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_emailreminderlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='doc_type',
        ),
        migrations.AddField(
            model_name='document',
            name='commencement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='commencement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ExpiryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_valid', models.PositiveIntegerField(help_text='Number of days this document is valid for')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.documenttype')),
                ('tenant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.tenanttype')),
            ],
        ),
    ]
