# Generated by Django 5.2.4 on 2025-08-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_remove_document_doc_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantExpiryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_valid', models.PositiveIntegerField()),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.documenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.tenant')),
            ],
        ),
    ]
