# Generated by Django 5.2.4 on 2025-08-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_tenantexpiryrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=50)),
                ('size_sqm', models.DecimalField(decimal_places=2, help_text='Size in square metres', max_digits=10)),
                ('size_sqft', models.DecimalField(decimal_places=2, editable=False, help_text='Size in square feet', max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='files.tenant')),
            ],
        ),
    ]
