# Generated by Django 5.2.4 on 2025-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='size_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in square feet', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='size_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in square metres', max_digits=10, null=True),
        ),
    ]
