# Generated by Django 5.2.4 on 2025-09-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_alter_unit_size_sqft_alter_unit_size_sqm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_view_analytics', 'Can view analytics')]},
        ),
    ]
