# Generated by Django 5.2.4 on 2025-09-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterField(
            model_name='document',
            name='commencement_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='commencement_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
