# Generated by Django 5.2.4 on 2025-09-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_document_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_type', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='archives/')),
                ('upload_date', models.DateField()),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
