# Generated by Django 5.2.4 on 2025-09-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_archiveddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='commencement_date',
            field=models.DateField(blank=True, help_text='Rent commencement date', null=True),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='escalation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escalation rate in % (e.g., 5.00 for 5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='commencement_date',
            field=models.DateField(blank=True, help_text='Rent commencement date', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='escalation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escalation rate in % (e.g., 5.00 for 5%)', max_digits=5, null=True),
        ),
    ]
